### ISSUE TITLE
Contributing to the project

### ISSUE THREAD

**Issue by marcosfelt** [OpenChemistry/edp#77]
If this is what it seems, I've bee looking to building something along these lines. Are you looking for any open-source contributors?

**Comment by cryos** [comment]
Sorry about the delay in replying, we were moving offices, time out of the office... The code developed here is intended to be open, but fairly focused on a few data sets we are working on. It may not be the best stage to contribute, but certainly open to contributions and input. We also welcome you reusing the code developed here.
